name: PEng-2023
channels:
- conda-forge
dependencies:
- python>=3.11
- pip

  # main packages
- numpy
- scipy
- pandas>=2.0
- shapely
- yaml
- sshtunnel
- folium
- haversine
- dash
- dash-bootstrap-components

 # database
- psycopg2
- sqlalchemy>=2.0
- geoalchemy2

  # interactive python
- ipython
- jupyterlab

  # plotting
- matplotlib
- plotly

  # publishing
- jupyter-book
- ghp-import
- notebook
